### ISSUE TITLE
[Bug]: manifest v3 issues (Self-hosted Extension) checklist before deployment.

### ISSUE THREAD

**Issue by incpi** [dbeck121/CPI-Helper-Chrome-Extension#182]
**Bugs + Checklist**

- [x] Extension needs to self-hosted as prerequisite.
    - [x] Fomantic UI is not complete/ self hosted. (CDN to self host)
- [x] Need to modify fix issue
    - [x] The set icon fails in mv3
    - [x] count has issues update as max instead of indented.
    - [x] popup active on another tab as well.

If you have any, please add in comments.

**Comment by anterchen** [comment]
in my case,the design page in the path of *.platform.Sapcloud.cn/shell/design/contentpackage/*, CPI Helper is not effective

**Comment by incpi** [comment]
Hello @anterchen,

This is checklist for manifest version 3 not the regarding deployment of current versions. We are deploying as of now with manifest v2 only.

Nevertheless, we don't have access to CN servers, please help me to verify it If this fixes the issue #189.

Thanks,
Omkar

**Comment by dbeck121** [comment]
@incpi 
Fix in last push to dev:

- The set icon fails in mv3
- count has issues update as max instead of indented.

**Comment by dbeck121** [comment]
Firefox has problems with background worker "not supported" in manifest v3

**Comment by incpi** [comment]
Firefox says no version 3 and google says no v2... most of us are chromium users So, that's why I said to do mv3 migration. Firefox we give limited support, most of our code is compatible except few web apis.
